analyze_board_minutes:
  description: >
    Analyze the provided club meeting minutes, following the structure and rules outlined in the sample PDF.
    Answer the user's question by carefully examining the text for specific details about motions, financial reports, officer updates, and action items.
    Pay special attention to motion numbers, voting outcomes, and financial figures from budget or fundraising accounts.

    Query: {query}
  expected_output: >
    A detailed and factual answer to the user's query, based *only* on the information present in the meeting minutes.
    The response should be specific, citing motion numbers, financial amounts, dates, and individuals involved, as found in the text.
    For example, when asked about a financial transaction, specify the amount, the account (budget or fundraising), the recipient, and the purpose of the payment.
  agent: board_minutes_analyst
