query_interaction_logs:
  description: >
    Answer the user's question by carefully analyzing the structured customer interaction logs.
    These may include calls, emails, meetings, LinkedIn messages, and more. Use reasoning to combine relevant entries
    and synthesize the most accurate, complete response possible, even if it spans multiple entries.
    Be precise and structured in your answer.
    
    Query: {query}
  expected_output: >
    A well-structured response that answers the question using facts found in the CRM interaction logs,
    including relevant dates, contacts, action items, objections, outcomes, and responsible team members.
  agent: crm_log_agent
